### ISSUE TITLE
Mod Compatibility

### ISSUE THREAD

**Issue by Nekonaro** [MCTeamPotato/Redirector#12]
Yes, I saw that you wrote that the mod is made to be compatible with everything. But I still wanted to clarify, are the following mods compatible?

I use the following mods:
Cleanroom
[https://github.com/Asek3/sodium-1.12](https://github.com/CleanroomMC/Cleanroom)

Vintagium
[https://github.com/Asek3/sodium-1.12](https://github.com/Asek3/sodium-1.12)

FermiumASM
[https://github.com/fonnymunkey/FermiumASM](https://github.com/fonnymunkey/FermiumASM)

Homoium
[https://github.com/HomoMC/Homoium](https://github.com/HomoMC/Homoium)

I also use
Alfheim and Valkyrie
[https://github.com/Red-Studio-Ragnarok/Alfheim](https://github.com/Red-Studio-Ragnarok/Alfheim)
[https://github.com/Red-Studio-Ragnarok/Valkyrie](https://github.com/Red-Studio-Ragnarok/Valkyrie)

If you have the opportunity, could you check these mods for compatibility with yours?

**Comment by erialsan** [comment]
The cause is likely to be Valkyrie and Fermium because their internal structure is older than that of Loli.

**Comment by Ecdcaeb** [comment]
> Yes, I saw that you wrote that the mod is made to be compatible with everything. But I still wanted to clarify, are the following mods compatible?

I think you may have misunderstood what I meant.
`Every crash` means to handle any crash that may be caused by redirectionor at any crash, which is a kind of automatic filling of configuration files based on fuzzy matching, which is similar to what was done manually in the past few issues. (https://github.com/Ecdcaeb/Redirector/issues/7)

By the way, while most crashes are exposed at bootstrap, there are still some crashes that occur during gameplay, but I didn't have a opportunity to test them in depth.
